sources:
  - name: staging
    schema: staging
    description: Сырые данные из пайплайна API -> S3 -> DWH
    tables:
      - name: crypto_prices_raw
        loaded_at_field: _loaded_at
        freshness:
          warn_after: {count: 2, period: hour}
          error_after: {count: 6, period: hour}
